clc;
clear all;
close all;
x=input('Enter the sequence:');
N=input('Enter the value of N:');
x=[x,zeros(1,N-length(x))];
subplot(2,2,1);
stem(x);
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('ORIGINAL SIGNAL');
grid on;
XK=dft(x,N);
disp(XK);
subplot(2,2,2);
stem(abs(XK));
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('DFT OF SIGNAL');
grid on;
[xn]=idft(XK,N);
disp(xn);
subplot(2,2,[3 4]);
stem(abs(xn));
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('IDFT OF SIGNAL');
grid on;