clc;
clear all;
close all;
n=[-3:2];
x=[1 2 3 4 5 6];
subplot(2,2,[1 2]);
stem(n,x);
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('Original Signal');
grid on;
[y,n]=sigfold(x,n);
disp(y);
subplot(2,2,[3 4]);
stem(n,y);
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('Folded Signal');
grid on;