clc;
clear all;
close all;
T=1;
wp=0.2*pi;
ws=0.6*pi;
e=sqrt(1/0.8^2-1);
A=1/0.2;
wp=wp/T;
ws=T;
N=ceil((1/2)*(log10(e^2/(A^2-1)))/(log10(wp/ws)));
wc=wp/((e^2)^(1/(2^N)));
[b,a]=butter(N,wc,'low','s');
Hs=tf(b,a);
[numd,dend]=impinvar(b,a,1/T);
Hz=tf(numd,dend,T);
w=0:0.01:pi;
Hw=freqz(numd,dend,w);
plot(w/pi,abs(Hw),'linewidth',2);
title('IIR Filter using Impulse Invariant Transformation Method');
xlabel('Frequency in pi units---->');
ylabel('Magnitude---->');
grid on;