clc;
clear all;
close all;
n1=[-3:2];
x1=[1 2 3 6 3 2];
subplot(2,2,1);
stem(n1,x1);
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('Original Signal x1');
grid on;
n2=[-1:5];
x2=[2 3 1 2 3 4 3];
subplot(2,2,2);
stem(n2,x2);
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('Original Signal x2');
grid on;
[y,n]=sigmult(x1,n1,x2,n2);
subplot(2,2,[3 4]);
stem(n,y);
disp(y);
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('Signal Multiplication');
grid on;