clc;
clear all;
close all;
n=[-3:2];
x=[1 2 3 4 5 6];
subplot(2,2,[1 2]);
stem(n,x);
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('Original Signal');
grid on;
k=input('Enter the values of k(i.e. the no. of shift):');
[y,n]=sigshift(x,n,k);
disp(y);
subplot(2,2,[3 4]);
stem(n,y);
xlabel('Number of Samples----->');
ylabel('Amplitude----->');
title('Shifted Signal');
grid on;